"""refactores order

Revision ID: 0963613a981b
Revises: 349738a23426
Create Date: 2026-04-02 16:46:21.556352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0963613a981b'
down_revision: Union[str, Sequence[str], None] = '349738a23426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_ibfk_2'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_ibfk_3'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_name')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('product_name', mysql.VARCHAR(length=200), nullable=True))
    op.create_foreign_key(op.f('orders_ibfk_3'), 'orders', 'products', ['product_name'], ['name'])
    op.create_foreign_key(op.f('orders_ibfk_2'), 'orders', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
