"""removed totalamount

Revision ID: 349738a23426
Revises: 492e11791bb9
Create Date: 2026-04-01 13:11:04.106417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '349738a23426'
down_revision: Union[str, Sequence[str], None] = '492e11791bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('total_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###
