"""added totalamount

Revision ID: 492e11791bb9
Revises: 1544fc508268
Create Date: 2026-04-01 13:01:59.720527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492e11791bb9'
down_revision: Union[str, Sequence[str], None] = '1544fc508268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('total_amount', sa.DECIMAL(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'total_amount')
    # ### end Alembic commands ###
