"""add category table

Revision ID: 6214d3c05486
Revises: 
Create Date: 2026-03-31 15:01:41.211192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6214d3c05486'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('products', sa.Column(
    # 'category_id', sa.Integer(), nullable=True))
    # op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_unique_constraint(None, 'products', ['name'])
    op.create_foreign_key(None, 'products', 'categories',
                          ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='unique')
    op.create_index(op.f('ix_products_name'),
                    'products', ['name'], unique=False)
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
