"""removed product name from order item

Revision ID: b30c40087676
Revises: 0963613a981b
Create Date: 2026-04-02 18:29:37.493000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b30c40087676'
down_revision: Union[str, Sequence[str], None] = '0963613a981b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'product_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_name', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
